num_cpus: 1
num_gpus: 1
num_workers: 0
local_mode: false
verbose: 1
visualize: false
debug: False
framework: tf
shared_base_model: true
timesteps: 1000000
gamma: 0.99
beta: null
initial_beta: 0.01  # Important to set small. Otherwise "slave" members get a "bump" at the beginning
local_dir: none
checkpoint_dir: null
checkpoint_freq: 0
buffer_size: 200000
tail_queue_size: 10000
multi_binary: True
entropy_lr: .0000625
lr: .0000625
adam_epsilon: .00015
double_q: true
dueling: false
num_atoms: 1
noisy: false
prioritized_replay: false
n_step: 1
target_network_update_freq: 8000
learning_starts: 20000
rollout_fragment_length: 4
train_batch_size: 32
exploration_config:
  epsilon_timesteps: 200000
  initial_epsilon: 0.01
  final_epsilon: 0.01
prioritized_replay_alpha: 0.5
final_prioritized_replay_beta: 1.0
prioritized_replay_beta_annealing_timesteps: 2000000
timesteps_per_iteration: 10000
vis_sleep: 0.0
grid_repeats: 1

env:
  grid_search:
        - AirRaidNoFrameskip-v4  # hard
        - PrivateEyeNoFrameskip-v4  # hard
        - QbertNoFrameskip-v4  # hard
        - MontezumaRevengeNoFrameskip-v4  # hard

#        - AlienNoFrameskip-v4  # hard
#        - AmidarNoFrameskip-v4
#        - AsteroidsNoFrameskip-v4
#        - BreakoutNoFrameskip-v4
#        - BowlingNoFrameskip-v4
#        - DemonAttackNoFrameskip-v4
#        - FrostbiteNoFrameskip-v4
#        - GravitarNoFrameskip-v4
#        - KrullNoFrameskip-v4
#        - MsPacmanNoFrameskip-v4
#        - NameThisGameNoFrameskip-v4
#        - RiverraidNoFrameskip-v4
#        - RobotankNoFrameskip-v4
#        - SeaquestNoFrameskip-v4
#        - SpaceInvadersNoFrameskip-v4
#        - StarGunnerNoFrameskip-v4
#        - TennisNoFrameskip-v4
#        - TimePilotNoFrameskip-v4
#        - TutankhamNoFrameskip-v4
#        - WizardOfWorNoFrameskip-v4
ensemble_size:
  grid_search: [2, 3,4]
div_type:
  grid_search: [action, state]
target_div:
  grid_search: [0.8, 0.4, 0]

## Flat Debug Profile
#env: CartPole-v0
#ensemble_size: 2
#div_type: action
#target_div: 0.0

## Tune Debug Profile
#env: CartPole-v0
#ensemble_size:
#  grid_search: [1, 1]
#div_type:
#  grid_search: [action, action]
#target_div:
#  grid_search: [0.1, 0.1]