num_cpus: 0
num_gpus: 0
num_workers: 0
local_mode: false
verbose: false
env: BreakoutNoFrameskip-v4
debug: False
framework: tf
shared_base_model: true
ensemble_size: 1
multi_binary: True
timesteps: 1000000
gamma: 0.99
batch_size: 256
beta: None
initial_beta: 0.01
local_dir: none
checkpoint_dir: None
checkpoint_freq: 0
buffer_size: 100000
entropy_lr: .0000625
lr: .0000625
beta_learning_rate: .0000625
adam_epsilon: .00015
double_q: false
dueling: false
num_atoms: 1
noisy: false
prioritized_replay: false
n_step: 1
target_network_update_freq: 8000
learning_starts: 0
rollout_fragment_length: 4
train_batch_size: 32
exploration_config:
  epsilon_timesteps: 200000
  initial_epsilon: 0.01
  final_epsilon: 0.01
prioritized_replay_alpha: 0.5
final_prioritized_replay_beta: 1.0
prioritized_replay_beta_annealing_timesteps: 2000000
timesteps_per_iteration: 10000
vis_sleep: 0.0
object_store_memory: 1000000000